version: '3.8'

services:
  # 1. 데이터베이스 서비스
  my-db:
    image: postgres:15-alpine
    container_name: my-db
    networks:
      - my-room
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: deokhugam_db
    ports:
      - "5433:5432" # 로컬에서 DB 접속할 때를 위해 포트 오픈 (5432포트는 기존 스프린트 미션에서 사용중)

  # 2. 스프링부트 서버 서비스
  deokhugam-server:
    build: .
    container_name: deokhugam-server
    networks:
      - my-room
    depends_on:
      - my-db # DB가 먼저 켜진 다음에 서버를 켠다.
    ports:
      - "8081:8080"
    env_file:
      - .env # .env 파일에 적힌 값을 자동으로 읽어온다.

networks:
  my-room:
    driver: bridge